name: wizjs_flutter_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # webview插件
  webview_flutter: ">=3.0.0 <4.0.0"
  # 设备信息
  device_info_plus: ">=3.0.0 <4.0.0"
  # 版本信息
  package_info_plus: ">=1.0.0 <2.0.0"
  # 权限请求
  permission_handler: ">=8.0.0 <9.0.0"
  # 网络请求
  http: ">=0.0.1 <1.0.0"
  dio: ">=4.0.0 <5.0.0"
  # 网络日志
  dio_log: ">=2.0.0 <3.0.0"
  # 数据存储
  shared_preferences: ">=2.0.0 <3.0.0"
  # 文件路径
  path_provider: ">=2.0.0 <3.0.0"
  # 媒体保存
  image_gallery_saver: ">=1.0.0 <2.0.0"
  # 图片压缩
  flutter_image_compress: ">=1.0.0 <2.0.0"
  # 媒体选择
  image_picker: ">=0.0.1 <1.0.0"
  # 视频压缩
  video_compress: ">=3.0.0 <4.0.0"
  # 打开文件
  open_file: ">=3.0.0 <4.0.0"
  # 加密解密
  encrypt: ">=5.0.0 <6.0.0"
  # 文件压缩
  flutter_archive: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
